security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            login_link:
                check_route: security_login_check
                signature_properties: ['id']
            logout:
                path: security_logout
            oauth:
                resource_owners:
                    github: "/login/check-github"
                login_path: /login
                use_forward: false
                failure_path: /login

                oauth_user_provider:
                    service: oauth_user_provider


    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user/favorite, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
