version: '3.9'
services:
    redis:
        image: redis:6-alpine
        container_name: dev-conferences-app-redis
        restart: unless-stopped
        command: [ '--appendonly', 'yes' ]
        volumes:
            - .data/redis:/data
        networks:
            - dev-conferences-services

    php-fpm:
        build: docker/php-fpm
        container_name: dev-conferences-app-php-fpm
        restart: always
        links:
            - 'redis'
        working_dir: /application
        volumes:
            - ~/.ssh:/root/.ssh:ro
            - ./:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini
            - ./docker/php-fpm/docker-www.conf:/etc/php/8.4/fpm/conf.d/docker-www.conf
        user: "1000:1000"
        networks:
            - dev-conferences-services
        extra_hosts:
            - "api-devconf.traefik.me:host-gateway"

    webserver:
        image: nginx:alpine
        container_name: dev-conferences-app-webserver
        restart: always
        links:
            - 'php-fpm'
        working_dir: /application
        volumes:
            - ./:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - dev-conferences-certs:/certs
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=dev-conferences-traefik"
            - "traefik.http.routers.app.rule=Host(`devconf.traefik.me`)"
            - "traefik.http.routers.app.tls=true"
            - "traefik.http.services.app.loadbalancer.server.port=8080"
        networks:
            - dev-conferences-traefik
            - dev-conferences-services

volumes:
    dev-conferences-certs:
        external: true

networks:
    dev-conferences-services:
        external: true
    dev-conferences-traefik:
        external: true
