name: CI

on: [push]

jobs:
  build-and-push-prod-images:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker build -t ghcr.io/muhtreb/dev-conferences-app-symfony/webserver:latest -f docker/prod/webserver/Dockerfile .
      - run: echo "Images have been built"
      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u muhtreb --password-stdin
      - run: |
          docker push ghcr.io/muhtreb/dev-conferences-app-symfony/webserver:latest
      - run: echo "Images have been pushed"